# Generated by Django 5.1.1 on 2024-10-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
