# Generated by Django 5.1.1 on 2024-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=29)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
